import { apiFetch } from './api.js';
import { SESSION_KEY, ROLE_LABELS } from './config.js';
import { initTheme, toggleTheme } from './theme.js';
const state={user:null,books:[],categories:[],loans:[],users:[],movements:[],dashboard:{},tab:'dashboard'};
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
export const App={
 async init(){initTheme();const saved=localStorage.getItem(SESSION_KEY);if(saved){try{state.user=JSON.parse(saved)}catch{localStorage.removeItem(SESSION_KEY)}}this.bindNavigation();if(state.user)await this.showApp();else this.showLogin()},
 toggleTheme(){toggleTheme()},
 showLogin(){ $('login-page').style.display='flex';$('app-shell').style.display='none';$('login-page').innerHTML=`<div class="login-card"><div class="brand-mark">📚</div><span class="eyebrow">CONTROLE DE BIBLIOTECA</span><h1>Acervo & Estoque</h1><p>Entre para administrar livros, empréstimos e movimentações.</p><form id="login-form"><label>E-mail<input name="email" type="email" required placeholder="admin@biblioteca.local"></label><label>Senha<input name="password" type="password" required placeholder="••••••••"></label><button class="btn primary" type="submit">Entrar</button><div id="login-error" class="error"></div></form><button class="theme-btn" type="button" onclick="App.toggleTheme()">Alternar tema</button></div>`;$('login-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),err=$('login-error');err.textContent='';try{const r=await apiFetch('/auth/login',{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});state.user=r.user;localStorage.setItem(SESSION_KEY,JSON.stringify(state.user));await this.showApp()}catch(x){err.textContent=x.message}})},
 async showApp(){$('login-page').style.display='none';$('app-shell').style.display='block';$('user-name').textContent=state.user.name;$('user-role').textContent=ROLE_LABELS[state.user.role]||state.user.role;document.querySelectorAll('[data-admin]').forEach(x=>x.style.display=state.user.role==='admin'?'':'none');await this.loadAll();this.render()},
 logout(){localStorage.removeItem(SESSION_KEY);location.reload()},
 bindNavigation(){document.addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;state.tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===state.tab));this.render()})},
 async loadAll(){const [dashboard,books,categories,loans,users,movements]=await Promise.all([apiFetch('/dashboard'),apiFetch('/books'),apiFetch('/categories'),apiFetch('/loans'),apiFetch('/users'),apiFetch('/stock-movements')]);Object.assign(state,{dashboard,books,categories,loans,users,movements})},
 async refresh(){await this.loadAll();this.render()},
 render(){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));const v=$(`view-${state.tab}`);if(v)v.classList.add('active');({dashboard:this.renderDashboard,books:this.renderBooks,loans:this.renderLoans,movements:this.renderMovements,categories:this.renderCategories,users:this.renderUsers}[state.tab]||this.renderDashboard).call(this)},
 renderDashboard(){const d=state.dashboard||{};$('dash-cards').innerHTML=[['Livros ativos',d.total_books,'📚'],['Exemplares',d.total_copies,'📦'],['Disponíveis',d.available_copies,'✓'],['Empréstimos ativos',d.active_loans,'↗'],['Em atraso',d.overdue_loans,'!'],['Estoque baixo',d.low_stock_books,'⚠']].map(([l,v,i])=>`<div class="stat"><span>${i}</span><div><small>${l}</small><strong>${v??0}</strong></div></div>`).join('');$('dashboard-table').innerHTML=state.loans.slice(0,6).map(l=>`<tr><td><strong>${esc(l.book_title)}</strong><small>${esc(l.book_author)}</small></td><td>${esc(l.borrower_name)}</td><td>${l.status==='active'?'<b class="pill green">Ativo</b>':'<b class="pill">Devolvido</b>'}</td><td>${l.due_date}</td></tr>`).join('')||'<tr><td colspan="4">Nenhum empréstimo.</td></tr>'},
 renderBooks(){const q=($('book-search')?.value||'').toLowerCase();const rows=state.books.filter(b=>`${b.title} ${b.author} ${b.category_name}`.toLowerCase().includes(q));$('books-table').innerHTML=rows.map(b=>`<tr><td><strong>${esc(b.title)}</strong><small>${esc(b.author)}</small></td><td>${esc(b.category_name)}</td><td>${b.quantity}</td><td>${b.available_quantity}</td><td>${b.available_quantity<=b.minimum_quantity?'<span class="pill warn">Baixo</span>':'<span class="pill green">Normal</span>'}</td><td>${b.active?'<span class="pill green">Ativo</span>':'<span class="pill">Inativo</span>'}</td><td><button class="icon-btn" onclick="App.editBook(${b.id})">Editar</button>${b.active?`<button class="icon-btn danger" onclick="App.inactivateBook(${b.id})">Inativar</button>`:''}</td></tr>`).join('')||'<tr><td colspan="7">Nenhum livro encontrado.</td></tr>'},
 renderLoans(){const today=new Date().toISOString().slice(0,10);$('loans-table').innerHTML=state.loans.map(l=>`<tr><td><strong>${esc(l.book_title)}</strong><small>${esc(l.book_author)}</small></td><td>${esc(l.borrower_name)}<small>${esc(l.borrower_registration||'')}</small></td><td>${l.loan_date}</td><td>${l.due_date}</td><td>${l.status==='active'?(l.due_date<today?'<span class="pill warn">Atrasado</span>':'<span class="pill green">Ativo</span>'):'<span class="pill">Devolvido</span>'}</td><td>${l.status==='active'?`<button class="icon-btn" onclick="App.returnLoan(${l.id})">Registrar devolução</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="6">Nenhum empréstimo.</td></tr>'},
 renderMovements(){$('movements-table').innerHTML=state.movements.map(m=>`<tr><td>${new Date(m.created_at).toLocaleString('pt-BR')}</td><td>${esc(m.book_title)}</td><td>${esc(m.type)}</td><td>${m.quantity}</td><td>${esc(m.reason||'')}</td><td>${esc(m.user_name||'—')}</td></tr>`).join('')||'<tr><td colspan="6">Nenhuma movimentação.</td></tr>'},
 renderCategories(){$('categories-table').innerHTML=state.categories.map(c=>`<tr><td>${c.id}</td><td><strong>${esc(c.name)}</strong></td><td>${esc(c.description||'')}</td><td><button class="icon-btn" onclick="App.editCategory(${c.id})">Editar</button><button class="icon-btn danger" onclick="App.deleteCategory(${c.id})">Excluir</button></td></tr>`).join('')},
 renderUsers(){$('users-table').innerHTML=state.users.map(u=>`<tr><td><strong>${esc(u.name)}</strong><small>${esc(u.email)}</small></td><td>${ROLE_LABELS[u.role]||u.role}</td><td>${u.active?'<span class="pill green">Ativo</span>':'<span class="pill">Inativo</span>'}</td><td><button class="icon-btn" onclick="App.editUser(${u.id})">Editar</button></td></tr>`).join('')},
 openModal(title,html){$('modal-title').textContent=title;$('modal-body').innerHTML=html;$('modal').classList.add('open')},closeModal(){$('modal').classList.remove('open')},
 field(label,name,value='',req=false,type='text'){return `<label>${label}${req?' *':''}<input name="${name}" type="${type}" value="${esc(value)}" ${req?'required':''}></label>`},
 openBookModal(id=null){const b=id?state.books.find(x=>x.id===id):{};this.openModal(id?'Editar livro':'Novo livro',`<form id="book-form" class="form-grid">${this.field('Título','title',b.title||'',true)}${this.field('Autor','author',b.author||'',true)}${this.field('ISBN','isbn',b.isbn||'')}${this.field('Editora','publisher',b.publisher||'')}${this.field('Ano de publicação','publication_year',b.publication_year||'',false,'number')}${this.field('Quantidade','quantity',b.quantity??0,true,'number')}${this.field('Mínimo no estoque','minimum_quantity',b.minimum_quantity??2,false,'number')}<label>Categoria *<select name="category_id" required>${state.categories.map(c=>`<option value="${c.id}" ${c.id===b.category_id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label class="full">Descrição<textarea name="description">${esc(b.description||'')}</textarea></label><div class="full form-actions"><button class="btn primary">Salvar</button><button type="button" class="btn" onclick="App.closeModal()">Cancelar</button></div></form>`);$('book-form').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));f.category_id=Number(f.category_id);f.quantity=Number(f.quantity);f.minimum_quantity=Number(f.minimum_quantity);f.publication_year=f.publication_year?Number(f.publication_year):null;f.active=id?b.active:true;try{await apiFetch(id?`/books/${id}`:'/books',{method:id?'PUT':'POST',body:JSON.stringify(f)});this.closeModal();await this.refresh()}catch(x){alert(x.message)}})},
 editBook(id){this.openBookModal(id)},
 async inactivateBook(id){if(!confirm('Inativar este livro?'))return;try{await apiFetch(`/books/${id}`,{method:'DELETE'});await this.refresh()}catch(e){alert(e.message)}},
 openLoanModal(){const active=state.books.filter(b=>b.active&&b.available_quantity>0);if(!active.length){alert('Não há livros disponíveis para empréstimo.');return}const minDate=new Date();minDate.setDate(minDate.getDate()+7);const due=minDate.toISOString().slice(0,10);this.openModal('Novo empréstimo',`<form id="loan-form" class="form-grid"><label>Livro *<select name="book_id" required>${active.map(b=>`<option value="${b.id}">${esc(b.title)} — ${b.available_quantity} disponível(is)</option>`).join('')}</select></label>${this.field('Nome do responsável','borrower_name','',true)}${this.field('Matrícula','borrower_registration','')}${this.field('Data de devolução','due_date',due,true,'date')}<div class="full form-actions"><button class="btn primary">Registrar empréstimo</button><button type="button" class="btn" onclick="App.closeModal()">Cancelar</button></div></form>`);$('loan-form').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));f.book_id=Number(f.book_id);f.user_id=state.user.id;try{await apiFetch('/loans',{method:'POST',body:JSON.stringify(f)});this.closeModal();await this.refresh()}catch(x){alert(x.message)}})},
 async returnLoan(id){if(!confirm('Confirmar devolução deste empréstimo?'))return;try{await apiFetch(`/loans/${id}/return`,{method:'PUT',body:JSON.stringify({user_id:state.user.id})});await this.refresh()}catch(e){alert(e.message)}},
 openCategoryModal(id=null){const c=id?state.categories.find(x=>x.id===id):{};this.openModal(id?'Editar categoria':'Nova categoria',`<form id="cat-form">${this.field('Nome','name',c.name||'',true)}<label>Descrição<textarea name="description">${esc(c.description||'')}</textarea></label><div class="form-actions"><button class="btn primary">Salvar</button><button type="button" class="btn" onclick="App.closeModal()">Cancelar</button></div></form>`);$('cat-form').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));try{await apiFetch(id?`/categories/${id}`:'/categories',{method:id?'PUT':'POST',body:JSON.stringify(f)});this.closeModal();await this.refresh()}catch(x){alert(x.message)}})},editCategory(id){this.openCategoryModal(id)},async deleteCategory(id){if(!confirm('Excluir esta categoria?'))return;try{await apiFetch(`/categories/${id}`,{method:'DELETE'});await this.refresh()}catch(e){alert(e.message)}},
 openUserModal(id=null){const u=id?state.users.find(x=>x.id===id):{};this.openModal(id?'Editar usuário':'Novo usuário',`<form id="user-form" class="form-grid">${this.field('Nome','name',u.name||'',true)}${this.field('E-mail','email',u.email||'',true,'email')}${this.field('Senha','password','',!id,'password')}<label>Função<select name="role"><option value="staff" ${u.role==='staff'?'selected':''}>Bibliotecário</option><option value="admin" ${u.role==='admin'?'selected':''}>Administrador</option></select></label><label>Status<select name="active"><option value="true" ${u.active!==false?'selected':''}>Ativo</option><option value="false" ${u.active===false?'selected':''}>Inativo</option></select></label><div class="full form-actions"><button class="btn primary">Salvar</button><button type="button" class="btn" onclick="App.closeModal()">Cancelar</button></div></form>`);$('user-form').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));f.active=f.active==='true';if(!f.password)delete f.password;try{await apiFetch(id?`/users/${id}`:'/users',{method:id?'PUT':'POST',body:JSON.stringify(f)});this.closeModal();await this.refresh()}catch(x){alert(x.message)}})},editUser(id){this.openUserModal(id)}
}; window.App=App;
